Repository Spring-2021-CISC374/construction_crew, pull requests merged in 2021-05, with the labels that each got.

#57 Anim levels Issue #48
  assets/images/speech.png
  scripts/scenes/PreloadScene.js
  scripts/scenes/levels/LevelFive.js
  scripts/scenes/levels/LevelFour.js
  scripts/scenes/levels/LevelOne.js
  scripts/scenes/levels/LevelSeven.js
  scripts/scenes/levels/LevelSix.js
  scripts/scenes/levels/LevelThree.js
  scripts/scenes/levels/LevelTwo.js
Labels: documentation, enhancement

#60 Audio
  assets/sounds/background_sound.mp3
  assets/sounds/drills.mp3
  scripts/scenes/MainMenu.js
  scripts/scenes/levels/Build.js
Labels: enhancement

#61 Progress
  scripts/scenes/Calendar.js
  scripts/scenes/levels/LevelFive.js
  scripts/scenes/levels/LevelSeven.js
  scripts/scenes/levels/LevelSix.js
Labels: bug, documentation, enhancement, help wanted

#77 Added a Hint into Wrong Page
  scripts/scenes/Calendar.js
  scripts/scenes/levels/Build.js
Labels: documentation, enhancement

#79 farmer->framer, fixed level intros #67
  assets/images/framer.png
  scripts/scenes/Calendar.js
  scripts/scenes/PreloadScene.js
  scripts/scenes/levels/LevelFive.js
  scripts/scenes/levels/LevelFour.js
  scripts/scenes/levels/LevelOne.js
  scripts/scenes/levels/LevelSeven.js
  scripts/scenes/levels/LevelSix.js
  scripts/scenes/levels/LevelThree.js
Labels: bug, documentation

#84 Added function for muting/unmuting sound.
  scripts/scenes/MainMenu.js
Labels: documentation, enhancement

#82 Fixing Bits and Pieces
  .DS_Store
  README.md
  assets/.DS_Store
  assets/images/volumeOff.png
  assets/images/volumeOn.jpg
  assets/images/volumeOn.png
  scripts/scenes/Calendar.js
  scripts/scenes/PreloadScene.js
  scripts/scenes/levels/LevelFive.js
  scripts/scenes/levels/LevelSeven.js
  scripts/scenes/levels/LevelSix.js
Labels: documentation, enhancement
